# 描述 Compose 文件的版本信息
version: "3.1"
# 定义服务，可以多个
services:
  redis-cluster:
    image: redis:6
    command: redis-cli -a 1234  --cluster create 192.168.91.131:6379 192.168.91.131:6380 192.168.91.131:6381 192.168.91.131:6382 192.168.91.131:6383 192.168.91.131:6384 --cluster-replicas 1  --cluster-yes
    depends_on:
      - redis-6379
      - redis-6380
      - redis-6381
      - redis-6382
      - redis-6383
      - redis-6384
  redis-6379: # 服务名称
    image: redis:6 # 创建容器时所需的镜像
    container_name: redis-6379 # 容器名称
    ports:
      - "6379:6379"
      - "16379:16379"
    volumes: # 数据卷，目录挂载
      - /root/redis-cluster/redis_6379.conf:/etc/redis/redis.conf
    command: redis-server /etc/redis/redis.conf # 覆盖容器启动后默认执行的命令

  redis-6380:
    image: redis:6
    container_name: redis-6380
    ports:
      - "6380:6380"
      - "16380:16380"
    volumes:
      - ./redis_6380.conf:/etc/redis/redis.conf
    command: redis-server /etc/redis/redis.conf

  redis-6381:
    image: redis:6
    container_name: redis-6381
    ports:
      - "6381:6381"
      - "16381:16381"
    volumes:
      - /root/redis-cluster/redis_6381.conf:/etc/redis/redis.conf
    command: redis-server /etc/redis/redis.conf

  redis-6382:
    image: redis:6
    container_name: redis-6382
    ports:
      - "6382:6382"
      - "16382:16382"
    volumes:
      - /root/redis-cluster/redis_6382.conf:/etc/redis/redis.conf
    command: redis-server /etc/redis/redis.conf

  redis-6383:
    image: redis:6
    container_name: redis-6383
    ports:
      - "6383:6383"
      - "16383:16383"
    volumes:
      - /root/redis-cluster/redis_6383.conf:/etc/redis/redis.conf
    command: redis-server /etc/redis/redis.conf

  redis-6384:
    image: redis:6
    container_name: redis-6384
    ports:
      - "6384:6384"
      - "16384:16384"
    volumes:
      - /root/redis-cluster/redis_6384.conf:/etc/redis/redis.conf
    command: redis-server /etc/redis/redis.conf
