version: '3'
services:
  apollo-portal:
    image: apolloconfig/apollo-portal:2.1.0
    container_name: apollo-portal
    restart: always
    ports:
      - "8070:8070"
    environment:
      DS_URL: "jdbc:mysql://192.168.91.131:3306/ApolloPortalDB?characterEncoding=utf8"
      DS_USERNAME: "root"
      DS_PASSWORD: "123456"
      APOLLO_PORTAL_ENVS: "DEV"
      DEV_META: "http://192.168.91.131:8080"
      #SERVER_SERVLET_CONTEXT_PATH: "/apollo"
    depends_on:
      - apollo-adminservice

  apollo-configservice:
    image: apolloconfig/apollo-configservice:2.1.0
    container_name: apollo-configservice
    restart: always
    ports:
      - "8080:8080"
    environment:
      SERVER_PORT: 8080
      EUREKA_INSTANCE_IP_ADDRESS: 192.168.91.131
      EUREKA_INSTANCE_HOME_PAGE_URL: "http://192.168.91.131:8080"
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "false"
      SPRING_DATASOURCE_URL: 'jdbc:mysql://192.168.91.131:3306/ApolloConfigDB?characterEncoding=utf8'
      SPRING_DATASOURCE_USERNAME: 'root'
      SPRING_DATASOURCE_PASSWORD: '123456'
    depends_on:
      - apollo-db

  apollo-adminservice:
    image: apolloconfig/apollo-adminservice:2.1.0
    container_name: apollo-adminservice
    restart: always
    ports:
      - "8090:8090"
    environment:
      SERVER_PORT: 8090
      EUREKA_INSTANCE_IP_ADDRESS: 192.168.91.131
      EUREKA_INSTANCE_HOME_PAGE_URL: "http://192.168.91.131:8090"
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "false"
      SPRING_DATASOURCE_URL: 'jdbc:mysql://192.168.91.131:3306/ApolloConfigDB?characterEncoding=utf8'
      SPRING_DATASOURCE_USERNAME: 'root'
      SPRING_DATASOURCE_PASSWORD: '123456'
    depends_on:
      - apollo-configservice

  apollo-db:
    image: apollo-mysql:latest
    container_name: apollo-db
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3306:3306"



