version: '3'
services:
  docker-fe-01:
    image: "apache/doris:2.0.0_alpha-fe-x86_64"
    container_name: "fe1"
    restart: always
    environment:
      - FE_SERVERS=fe1:172.20.80.2:9010,fe2:172.20.80.3:9010,fe3:172.20.80.4:9010
      - FE_ID=1
    ports:
      - 8031:8030
      - 9031:9030
    networks:
      doris_net:
        ipv4_address: 172.20.80.2
  docker-fe-02:
    image: "apache/doris:2.0.0_alpha-fe-x86_64"
    container_name: "fe2"
    restart: always
    environment:
      - FE_SERVERS=fe1:172.20.80.2:9010,fe2:172.20.80.3:9010,fe3:172.20.80.4:9010
      - FE_ID=2
    ports:
      - 8032:8030
      - 9032:9030
    networks:
      doris_net:
        ipv4_address: 172.20.80.3
  docker-fe-03:
    image: "apache/doris:2.0.0_alpha-fe-x86_64"
    container_name: "fe3"
    restart: always
    environment:
      - FE_SERVERS=fe1:172.20.80.2:9010,fe2:172.20.80.3:9010,fe3:172.20.80.4:9010
      - FE_ID=3
    ports:
      - 8033:8030
      - 9033:9030
    networks:
      doris_net:
        ipv4_address: 172.20.80.4
  docker-be-01:
    image: "apache/doris:2.0.0_alpha-be-x86_64"
    container_name: "doris-be-01"
    hostname: "be-01"
    depends_on:
      - docker-fe-01
      - docker-fe-02
      - docker-fe-03
    environment:
      - FE_SERVERS=fe1:172.20.80.2:9010,fe2:172.20.80.3:9010,fe3:172.20.80.4:9010
      - BE_ADDR=172.20.80.5:9050
    ports:
      - 8041:8040
    networks:
      doris_net:
        ipv4_address: 172.20.80.5
  docker-be-02:
    image: "apache/doris:2.0.0_alpha-be-x86_64"
    container_name: "doris-be-02"
    hostname: "be-02"
    depends_on:
      - docker-fe-01
      - docker-fe-02
      - docker-fe-03
    environment:
      - FE_SERVERS=fe1:172.20.80.2:9010,fe2:172.20.80.3:9010,fe3:172.20.80.4:9010
      - BE_ADDR=172.20.80.6:9050
    ports:
      - 8042:8040
    networks:
      doris_net:
        ipv4_address: 172.20.80.6
  docker-be-03:
    image: "apache/doris:2.0.0_alpha-be-x86_64"
    container_name: "doris-be-03"
    hostname: "be-03"
    depends_on:
      - docker-fe-01
      - docker-fe-02
      - docker-fe-03
    environment:
      - FE_SERVERS=fe1:172.20.80.2:9010,fe2:172.20.80.3:9010,fe3:172.20.80.4:9010
      - BE_ADDR=172.20.80.7:9050
    ports:
      - 8043:8040
    networks:
      doris_net:
        ipv4_address: 172.20.80.7

  doris-mysql:
    image: mysql:5.7
    container_name: "client"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    networks:
      doris_net:
        ipv4_address: 172.20.80.8

networks:
  doris_net:
    ipam:
      config:
        - subnet: 172.20.80.0/24


# doris启动后不需要配置，直接使用就行
# 注意：启动前，要保证机器上有足够的磁盘空间，不然会启动失败
# be启动失败：  Please set vm.max_map_count to be 2000000 under root using 'sysctl -w vm.max_map_count=2000000'.



# 9010 是fe之间的通讯端口
# 9050 是be的通讯端口？

# mysql 需要连接fe的 9030 端口，， mysql -uroot -h fe1 -P 9030
# 查看fe状态，，，                show proc '/frontends';
# 查看be状态，，，                show proc '/backends';

# 界面访问fe      用户名为root, 密码为空               http://192.168.91.131:8031/frontend
# 界面访问be      用户名为root, 密码为空               http://192.168.91.131:8031/backend



