version: '3.1'
services:
  redis6:
    image: redis:6
    container_name: redis6
    restart: always
    ports:
      - '6379:6379'
  MySQL8:
    image: mysql:8
    restart: always
    container_name: MySQL8
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
    ports:
      - '3306:3306'
    volumes:
      - /tmp/mysql/data:/var/lib/mysql
      - /tmp/mysql/conf:/etc/mysql/conf.d
      - /tmp/mysql/logs:/logs
  zookeeper:
    image: zookeeper:3.6.4
    restart: always
    container_name: zookeeper
    ports:
      - "2181:2181"
  elasticsearch:
    image: elasticsearch:7.8.0
    container_name: elasticsearch
    restart: always
    environment:
      - bootstrap.memory_lock=true
     # - "ES_JAVA_OPTS=-Xms2048m -Xmx2048m"
      - discovery.type=single-node
    volumes:
      - /tmp/es/data:/usr/share/elasticsearch/data
      - /tmp/es/logs:/usr/share/elasticsearch/logs
      - /tmp/es/plugins:/usr/share/elasticsearch/plugins
    ports:
      - '9200:9200'
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=123456
    ports:
      - '5672:5672'
      - '15672:15672'