version: "3.1"
services:
  node-exporter:
    image: prom/node-exporter:latest
    container_name: "node-exporter"
    ports:
      - "9100:9100"

  pushgateway:
    image: prom/pushgateway:latest
    container_name: "pushgateway"
    command: --persistence.file=/pushgateway/pushgateway.data
    ports:
      - "9091:9091"

  alertmanager:
    image: prom/alertmanager:latest
    container_name: "alertmanager"
    command: --config.file=/etc/alertmanager/alertmanager.yml
    ports:
      - "9093:9093"

  prometheus:
    image: prom/prometheus:latest
    container_name: "prometheus"
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml


  grafana:
    image: grafana/grafana:latest
    container_name: "grafana"
    ports:
      - "3000:3000"

# prometheus http://127.0.0.0:9090/
# grafana http://127.0.0.1:3000/  admin/admin