version: "3.1"
services:
  node-exporter:
    image: prom/node-exporter:latest
    container_name: "node-exporter"
    ports:
      - "9100:9100"
    restart: always
    networks:
      - prometheus-net

  prometheus:
    image: prom/prometheus:latest
    container_name: "prometheus"
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - /root/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - prometheus-net

  grafana:
    image: grafana/grafana
    container_name: "grafana"
    ports:
      - "3000:3000"
    restart: always
    networks:
      - prometheus-net

# 创建网络
networks:
  prometheus-net:
    driver: bridge

# prometheus http://192.168.91.131:9090/
# grafana http://192.168.91.131:3000/  admin/admin