version: "3.1"
services:
  node-exporter:
    image: prom/node-exporter:latest
    container_name: "node-exporter"
    ports:
      - "9100:9100"
    restart: always
    networks:
      - prometheus-net

  prometheus:
    image: prom/prometheus:latest
    container_name: "prometheus"
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - /root/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - prometheus-net

  grafana:
    image: grafana/grafana:latest
    container_name: "grafana"
    ports:
      - "3000:3000"
    restart: always
    networks:
      - prometheus-net

  pushgateway:
    image: prom/pushgateway:latest
    container_name: "pushgateway"
    command: --persistence.file=/pushgateway/pushgateway.data
    ports:
      - "9091:9091"
    restart: always
    networks:
      - prometheus-net


  alertmanager:
    image: prom/alertmanager:latest
    container_name: "alertmanager"
    command: --config.file=/etc/alertmanager/alertmanager.yml
    ports:
      - "9093:9093"
    restart: always
    networks:
      - prometheus-net

# 创建网络
networks:
  prometheus-net:
    driver: bridge

# prometheus http://192.168.91.131:9090/
# grafana http://192.168.91.131:3000/  admin/admin