version: '3'

services:
  redis-node-1:
    image: redis:7
    command: redis-server --cluster-enabled yes --cluster-config-file /data/nodes.conf --cluster-node-timeout 5000 --appendonly yes
    volumes:
      - redis-data-1:/data
    ports:
      - "7000:6379"

  redis-node-2:
    image: redis:7
    command: redis-server --cluster-enabled yes --cluster-config-file /data/nodes.conf --cluster-node-timeout 5000 --appendonly yes
    volumes:
      - redis-data-2:/data
    ports:
      - "7001:6379"

  redis-node-3:
    image: redis:7
    command: redis-server --cluster-enabled yes --cluster-config-file /data/nodes.conf --cluster-node-timeout 5000 --appendonly yes
    volumes:
      - redis-data-3:/data
    ports:
      - "7002:6379"

  redis-node-4:
    image: redis:7
    command: redis-server --cluster-enabled yes --cluster-config-file /data/nodes.conf --cluster-node-timeout 5000 --appendonly yes
    volumes:
      - redis-data-4:/data
    ports:
      - "7003:6379"

  redis-node-5:
    image: redis:7
    command: redis-server --cluster-enabled yes --cluster-config-file /data/nodes.conf --cluster-node-timeout 5000 --appendonly yes
    volumes:
      - redis-data-5:/data
    ports:
      - "7004:6379"

  redis-node-6:
    image: redis:7
    command: redis-server --cluster-enabled yes --cluster-config-file /data/nodes.conf --cluster-node-timeout 5000 --appendonly yes
    volumes:
      - redis-data-6:/data
    ports:
      - "7005:6379"

volumes:
  redis-data-1:
  redis-data-2:
  redis-data-3:
  redis-data-4:
  redis-data-5:
  redis-data-6:

# 启动后随便进入一个容器，开始初始化
# redis-cli --cluster create redis-node-1:6379 redis-node-2:6379 redis-node-3:6379 redis-node-4:6379 redis-node-5:6379 redis-node-6:6379 --cluster-replicas 1

# 查看集群信息
# docker-compose exec redis-node-1 redis-cli -c
# 输入cluster info

#注意redis集群无法本地使用，因为它是返回的是容器中的ip，本地根本无法连接