version: "3"
services:
  mqnamesrv:
    image: apache/rocketmq:4.9.4
    container_name: mqnamesrv
    ports:
      - "9876:9876"
    environment:
      JAVA_OPT: -server -Xms512m -Xmx512m
    command: sh mqnamesrv
    networks:
      - rocketmq-net

  mqbroker1m:
    image: apache/rocketmq:4.9.4
    container_name: mqbroker1m
    ports:
      - "10909:10909"
      - "10911:10911"
      - "10912:10912"
    environment:
      JAVA_OPT_EXT: -server -Xms512M -Xmx512M -Xmn256m
    volumes:
      - ./2m-2s-async/broker-a.properties:/home/rocketmq/rocketmq-4.9.4/conf/broker.conf
    command: sh mqbroker -n mqnamesrv:9876 -c /home/rocketmq/rocketmq-4.9.4/conf/broker.conf
    depends_on:
      - mqnamesrv
    networks:
      - rocketmq-net

  mqbroker1s:
    image: apache/rocketmq:4.9.4
    container_name: mqbroker1s
    ports:
      - "11909:10909"
      - "11911:10911"
      - "11912:10912"
    environment:
      JAVA_OPT_EXT: -server -Xms512M -Xmx512M -Xmn256m
    volumes:
      - ./2m-2s-async/broker-a-s.properties:/home/rocketmq/rocketmq-4.9.4/conf/broker.conf
    command: sh mqbroker -n mqnamesrv:9876 -c /home/rocketmq/rocketmq-4.9.4/conf/broker.conf
    depends_on:
      - mqnamesrv
    networks:
      - rocketmq-net


  mqbroker2m:
    image: apache/rocketmq:4.9.4
    container_name: mqbroker2m
    ports:
      - "12909:10909"
      - "12911:10911"
      - "12912:10912"
    environment:
      JAVA_OPT_EXT: -server -Xms512M -Xmx512M -Xmn256m
    volumes:
      - ./2m-2s-async/broker-b.properties:/home/rocketmq/rocketmq-4.9.4/conf/broker.conf
    command: sh mqbroker -n mqnamesrv:9876 -c /home/rocketmq/rocketmq-4.9.4/conf/broker.conf
    depends_on:
      - mqnamesrv
    networks:
      - rocketmq-net

  mqbroker2s:
    image: apache/rocketmq:4.9.4
    container_name: mqbroker2s
    ports:
      - "13909:10909"
      - "13911:10911"
      - "13912:10912"
    environment:
      JAVA_OPT_EXT: -server -Xms512M -Xmx512M -Xmn256m
    volumes:
      - ./2m-2s-async/broker-b-s.properties:/home/rocketmq/rocketmq-4.9.4/conf/broker.conf
    command: sh mqbroker -n mqnamesrv:9876 -c /home/rocketmq/rocketmq-4.9.4/conf/broker.conf
    depends_on:
      - mqnamesrv
    networks:
      - rocketmq-net


  mqconsole:
    image: apacherocketmq/rocketmq-dashboard:latest
    container_name: dashboard
    ports:
      - "19876:19876"
    environment:
      JAVA_OPTS: -Dserver.port=19876 -Drocketmq.namesrv.addr=mqnamesrv:9876 -Dcom.rocketmq.sendMessageWithVIPChannel=false
    depends_on:
      - mqnamesrv
    networks:
      - rocketmq-net

networks:
  rocketmq-net:
    driver: bridge