version: '3.7'
services:
  # NameServer服务配置
  namesrv:
    image: apache/rocketmq:4.9.3
    container_name: rmqnamesrv
    ports:
      - "9876:9876"
    command: sh mqnamesrv

  # Broker服务配置
  broker:
    image: apache/rocketmq:4.9.3
    container_name: rmqbroker
    ports:
      - "10911:10911"  # Broker服务端口
      - "10909:10909"  # Broker HA服务端口
    environment:
      - "NAMESRV_ADDR=namesrv:9876"
      - "JAVA_OPTS=-Duser.home=/opt"
      - "JAVA_OPT_EXT=-server -Xms512m -Xmx512m -Xmn256m"
    command: sh mqbroker -n namesrv:9876 -c /home/rocketmq/rocketmq-4.9.3/conf/broker.conf


#查看 RocketMQ 的状态
# ./mqadmin clusterList -n namesrv:9876

#你也可以创建 Topic
# ./mqadmin updateTopic -n namesrv:9876 -c DefaultCluster -t testTopic