version: '3.7'
services:
  oap:
    image: apache/skywalking-oap-server:9.5.0
    container_name: skywalking-oap
    ports:
      - "12800:12800"  # OAP服务的gRPC端口
      - "11800:11800"  # OAP服务的HTTP端口
    environment:
      SW_STORAGE: elasticsearch  # 使用Elasticsearch作为存储
      SW_STORAGE_ES_CLUSTER_NODES: elasticsearch:9200  # 指定Elasticsearch节点
    depends_on:
      - elasticsearch

  ui:
    image: apache/skywalking-ui:9.5.0
    container_name: skywalking-ui
    ports:
      - "8080:8080"  # SkyWalking UI的HTTP端口
    environment:
      SW_OAP_ADDRESS: http://oap:12800  # 指定OAP的地址
    depends_on:
      - oap

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"  # Elasticsearch的HTTP端口
      - "9300:9300"  # Elasticsearch的TCP端口

