version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
    ports:
      - "3306:3306"

  elasticsearch:
    image: elasticsearch:6.6.1
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"

  job-manager:
    image: my-flink:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - JOB_MANAGER_RPC_ADDRESS=job-manager
    command: jobmanager
    ports:
      - "8081:8081"

  task-manager:
    image: my-flink:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - JOB_MANAGER_RPC_ADDRESS=job-manager
    command: taskmanager
    depends_on:
      - job-manager
