FROM flink:1.20.0



COPY flink-cdc-pipeline-connector-mysql-3.1.0.jar /opt/flink/lib/

COPY mysql-connector-j-8.0.33.jar /opt/flink/lib/

COPY flink-cdc-pipeline-connector-elasticsearch-3.2.0.jar /opt/flink/lib/