version: '3.8'

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
    ports:
      - "3306:3306"

  elasticsearch:
    image: elasticsearch:7.9.3
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"

  job-manager:
    image: flink:latest
    environment:
      - JOB_MANAGER_RPC_ADDRESS=job-manager
    command: jobmanager
    ports:
      - "8081:8081"

  task-manager:
    image: flink:latest
    environment:
      - JOB_MANAGER_RPC_ADDRESS=job-manager
    command: taskmanager
    depends_on:
      - job-manager
