version: '3.8'

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
    ports:
      - "3306:3306"

  elasticsearch:
    image: elasticsearch:7.9.3
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"

  flink-job-manager:
    image: flink:1.13-scala_2.11
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - FLINK_PROPERTIES=jobmanager.web.port:8081

  flink-task-manager:
    image: flink:1.13-scala_2.11
    depends_on:
      - flink-job-manager
    command: taskmanager
